title: be minimal, please!
author: esrmnt
url: https://blog.esrmnt.dev
baseurl: "" 
description: A minimal no-style blog to keep track of my thoughts.
permalink: 

favicon: "logo.png" 

remote_theme: riggraz/no-style-please 

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag