title: "esrmnt"
description: "notes to self"
author: "esrmnt"
url: "https://esrmnt.github.io"
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: null
permalink: /:year/:month/:day/:title/
timezone: Asia/Kolkata

# Exclude development files
exclude:
  - README.md

# RSS
feed:
  path: feed.xml